// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty;

  define(['underscore', 'jquery', 'carousel', 'lightbox'], function() {
    var APIManager;
    return APIManager = (function() {

      APIManager.prototype.xml_to_json = 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=8&q=';

      function APIManager(mediaElements) {
        this.mediaElements = mediaElements;
        this.instagramLoad = __bind(this.instagramLoad, this);

        this.youtubeLoad = __bind(this.youtubeLoad, this);

        this.googleLoad = __bind(this.googleLoad, this);

        this.twitterLoad = __bind(this.twitterLoad, this);

        this.twitterCreateUrl = __bind(this.twitterCreateUrl, this);

        this.googleCreateUrl = __bind(this.googleCreateUrl, this);

        this.instagramCreateUrl = __bind(this.instagramCreateUrl, this);

        this.youtubeCreateUrl = __bind(this.youtubeCreateUrl, this);

        this.apis = {
          'youtube': {
            baseUrl: 'https://gdata.youtube.com/feeds/api/videos?',
            maxResults: 5,
            createUrl: this.youtubeCreateUrl,
            load: this.youtubeLoad,
            element: this.mediaElements.youtube,
            title: 'Videos of '
          },
          'instagram': {
            baseUrl: 'https://api.instagram.com/v1/tags/',
            clientID: '729810e4ea4449abb6f63f99a35332f4',
            createUrl: this.instagramCreateUrl,
            load: this.instagramLoad,
            element: this.mediaElements.instagram,
            title: 'Pictures of '
          },
          'google': {
            baseUrl: 'http://news.google.com/news?',
            createUrl: this.googleCreateUrl,
            load: this.googleLoad,
            element: this.mediaElements.google,
            title: 'News of '
          },
          'twitter': {
            baseUrl: 'http://search.twitter.com/search.json?',
            createUrl: this.twitterCreateUrl,
            load: this.twitterLoad,
            element: this.mediaElements.twitter,
            title: 'Tweets of '
          }
        };
      }

      APIManager.prototype.load = function(topic) {
        var key, value, _ref, _results;
        _ref = this.apis;
        _results = [];
        for (key in _ref) {
          if (!__hasProp.call(_ref, key)) continue;
          value = _ref[key];
          value.element.prev().empty().append(value.title + topic);
          _results.push(this.apiCall(value, topic));
        }
        return _results;
      };

      APIManager.prototype.apiCall = function(api, topic) {
        return $.ajax(api.createUrl(topic), {
          type: "GET",
          dataType: "jsonp",
          cache: false,
          success: api.load
        });
      };

      APIManager.prototype.youtubeCreateUrl = function(topic) {
        return this.apis.youtube.baseUrl + ("q=" + topic + "&max-results=" + this.apis.youtube.maxResults + "&orderby=published&alt=json&v=2");
      };

      APIManager.prototype.instagramCreateUrl = function(topic) {
        return this.apis.instagram.baseUrl + ("" + topic + "/media/recent?client_id=" + this.apis.instagram.clientID);
      };

      APIManager.prototype.googleCreateUrl = function(topic) {
        return this.xml_to_json + this.encodeURL(this.apis.google.baseUrl + ("q=" + topic + "&output=rss"));
      };

      APIManager.prototype.twitterCreateUrl = function(topic) {
        return this.apis.twitter.baseUrl + ("q=" + topic + "&lang=en");
      };

      APIManager.prototype.encodeURL = function(url) {
        var encodedURL, l, _i, _len;
        encodedURL = [''];
        for (_i = 0, _len = url.length; _i < _len; _i++) {
          l = url[_i];
          encodedURL.push(l.charCodeAt().toString(16));
        }
        return encodedURL.join('%');
      };

      APIManager.prototype.twitterLoad = function(data) {
        var content, tweet, _i, _len, _ref;
        content = [];
        _ref = data.results;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tweet = _ref[_i];
          content.push("<li><div class='tweets'><img src='" + tweet.profile_image_url + "'/><span class='tweetUserName'>" + tweet.from_user + "</span><p class='tweetText'>" + tweet.text + "</p></div></li>");
        }
        $('.wrapper > ul', this.apis.twitter.element).empty().append(content.join(''));
        return this.apis.twitter.element.liquidcarousel({
          height: 200
        });
      };

      APIManager.prototype.googleLoad = function(data) {
        var content, nContent, news, _i, _len, _ref;
        content = [];
        _ref = data.responseData.feed.entries;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          news = _ref[_i];
          if (news.content.search('font-family:arial,sans-serif"><a ') === -1) {
            continue;
          }
          nContent = news.content.replace('<div style="padding-top:0.8em"><img alt="" height="1" width="1"></div>', '');
          nContent = nContent.replace(/<\/font><br><font size="-1"><a.*/, '</font></div></font></td></tr></tbody></table>');
          nContent = nContent.replace(/<td valign="top"/g, '<td valign="top" class="google_news"');
          content.push("<li>" + nContent + "</li>");
        }
        $('.wrapper > ul', this.apis.google.element).empty().append(content.join(''));
        return this.apis.google.element.liquidcarousel({
          height: 130
        });
      };

      APIManager.prototype.youtubeLoad = function(data) {
        var content, video, videoID, _i, _len, _ref;
        content = [];
        _ref = data.feed.entry;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          video = _ref[_i];
          videoID = video.id.$t.split(':');
          videoID = videoID[videoID.length - 1];
          content.push("<li><iframe type='text/html' width='640' height='390' src='http://www.youtube.com/embed/" + videoID + "' frameborder='0'></iframe></li>");
        }
        $('.wrapper > ul', this.apis.youtube.element).empty().append(content.join(''));
        return this.apis.youtube.element.liquidcarousel({
          height: 400
        });
      };

      APIManager.prototype.instagramLoad = function(data) {
        var content, imageUrl, img, _i, _len, _ref;
        content = [];
        _ref = data.data;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          img = _ref[_i];
          imageUrl = img.images.standard_resolution.url;
          content.push("<li><a href='" + imageUrl + "' rel='lightbox'><img src='" + imageUrl + "' alt='' /></a></li>");
        }
        $('.wrapper > ul', this.apis.instagram.element).empty().append(content.join(''));
        this.apis.instagram.element.liquidcarousel({
          height: 300
        });
        return $("a[rel*='lightbox']").lightBox();
      };

      return APIManager;

    })();
  });

}).call(this);
