// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  require.config({
    baseUrl: '.',
    paths: {
      domReady: 'lib/domReady',
      jquery: 'lib/jquery-1.8.0.min',
      underscore: 'lib/underscore-min',
      carousel: 'lib/jquery.liquidcarousel.pack',
      lightbox: 'lib/jquery.lightbox-0.5',
      createCloud: 'js/createCloud',
      APIManager: 'js/APIManager',
      topStories: 'js/topStories'
    }
  });

  require(['domReady!', 'jquery', 'underscore'], function(dom) {
    return require(['carousel', 'lightbox'], function() {
      return require(['createCloud', 'APIManager'], function(createCloudClass, APIManager) {
        var Main;
        Main = (function() {
          var manager;

          manager = null;

          function Main() {
            this.cloudCreated = __bind(this.cloudCreated, this);

            var mediaElements;
            mediaElements = {
              'youtube': $('#youtube'),
              'instagram': $('#instagram'),
              'google': $('#google'),
              'twitter': $('#twitter')
            };
            manager = new APIManager(mediaElements);
            new createCloudClass($('#cloud'), this.cloudCreated);
          }

          Main.prototype.cloudCreated = function() {
            var _this = this;
            $("#loadingCloud").css('display', 'none');
            $("#refreshButton").click(function() {
              return new createCloudClass($('#cloud'), _this.cloudCreated);
            });
            return $("#cloud span").click(function() {
              var img, mediaSection, selected;
              $('#selectTopicMessage').css('display', 'none');
              mediaSection = $('.mediaSection');
              mediaSection.css('display', 'block');
              img = '<img class="loaders" src="img/ajax-loader.gif" />';
              $('.wrapper > ul', mediaSection).empty().append(img);
              selected = $('.cloudSelected')[0];
              if (selected != null) {
                $(selected).removeClass('cloudSelected');
              }
              $(this).addClass('cloudSelected');
              return manager.load(this.innerHTML);
            });
          };

          return Main;

        })();
        return new Main();
      });
    });
  });

}).call(this);
